### ISSUE TITLE
playback not working

### ISSUE THREAD

**Issue by cirrusUK** [kulpae/cloudruby#13]
Hi
 Im on updated archlinux, suddenly playback does not work, stays at 00:00, idk if recent pkg update has b0rken something or what. downloads work but not playback. Happens on all 4 updated arch boxxen and on my Free BSD box, maybe the new mpg123 causing it ?

**Comment by magnific0** [comment]
I entcountered the same issue, I have looked into it closer and found out that it's a mpg123 playback issue if the stream is HTTPS. Although Soundcloud can perfectly work over HTTP, it redirected play requests to HTTPS. I have fixed this issue in my fork.

https://github.com/magnific0/cloudruby

**Comment by kulpae** [comment]
no way... you were working on it the same time I did :D 
I've already found the problem and have built a gstreamer backend which works fine with https. Almost done ;)
I'll add your changes to the mpg123 backend.
Thanks

**Comment by magnific0** [comment]
Haha, that is great! gstreamer sounds like a better long term solution. Looking forward to see the changes!

**Comment by kulpae** [comment]
Some time ago I moved to rubyspec file structure, therefore I applied the changed by hand. Thank you!
Sorry  I did it without merging your commit. Your efforts are not in the commit history yet, but I've added your name to author list as compensation ;)

**Comment by magnific0** [comment]
No problem and thanks :-). The gstreamer solution looks great too. I will look into your new version later and read up on rubyspec file structure.

**Comment by kulpae** [comment]
oh silly me, I meant the filesructure as gemspec requires it. d'oh ^^
